### ISSUE TITLE
Thymeleaf doesn't add CSRF tokens automatically

### ISSUE THREAD

**Issue by DanielGronau** [fjorum/fjorum#18]
According to its docs, Thymeleaf should add the CSRF tokens automatically to forms, but I have to add it manually.

**Comment by cm-rudolph** [comment]
Thymeleaf attaches the CSRF input element processing to the `th:action` attribute. If it isn't supplied, thymeleaf doesn't add the element.

**Comment by DanielGronau** [comment]
Thank you!
