### ISSUE TITLE
JPA Converter auto-apply

### ISSUE THREAD

**Issue by DanielGronau** [fjorum/fjorum#8]
I added a LocalDateTimeConverter "manually" to the affected columns. It seems it can be registered globally, too. would be nice to get this working.

**Comment by DanielGronau** [comment]
seems to work now

**Comment by cm-rudolph** [comment]
Just a hint: hibernate 5.0.0 will be released soon. It has an extra package for java 8 types, the converter will become unnecessary then. See [HHH-8844](https://hibernate.atlassian.net/browse/HHH-8844).
The artifact is

```
<groupId>org.hibernate</groupId>
<artifactId>hibernate-java8</artifactId>
```
